app/models.py
from flask_login import UserMixin
from sqlalchemy import Column, Integer, String, ForeignKey
from werkzeug.security import generate_password_hash, check_password_hash

from app import db

__basemodel = db.Model


class User(__basemodel, UserMixin):
    __tablename__ = 'Users'
    id = Column(Integer, primary_key=True)
    name = Column(String, unique=True)
    email = Column(String)
    password_hash = Column(String(128))
    role_id = Column(Integer, ForeignKey("Roles.id"))
    role = db.relationship("Role", uselist=False, backref="users")

    def __repr__(self):
        return f"Пользователь {self.username}"

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class Role(__basemodel):
    __tablename__ = 'Roles'
    id = Column(Integer, primary_key=True)
    name = Column(String, unique=True)
    access_level = Column(Integer)

app/forms.py
from flask_wtf import FlaskForm
from werkzeug.routing import ValidationError
from wtforms.fields import *
from wtforms.validators import DataRequired, Email

from app.models import User
from app.validators import *


class LoginForm(FlaskForm):
    _name = "Вход"
    email = StringField('Электронная почта', validators=[DataRequired(), Email()])
    password = PasswordField('Пароль', validators=[DataRequired()])
    remember_me = BooleanField('Запомнить меня')
    submit = SubmitField('Войти')

    def validate_password(self, password):
        user = User.query.filter_by(email=self.email.data).first()

        if not user or not user.check_password(password.data):
            raise ValidationError('Неверная электронная почта или неверен пароль.')


class RegistrationForm(FlaskForm):
    _name = "Регистрация"
    username = StringField('Имя пользователя', validators=[DataRequired()])
    email = EmailField("Электронная почта", validators=[DataRequired(), Email()])
    password = PasswordField('Пароль', validators=[DataRequired()])
    password2 = PasswordField('Повтор пароля', validators=[DataRequired()])
    remember_me = BooleanField('Запомнить меня')
    submit = SubmitField('Зарегистрироваться')

    def validate_username(self, username):
        user = User.query.filter_by(name=username.data).first()
        if user:
            raise ValidationError('Это имя пользователя занято')

    def validate_password2(self, password):
        if password.data != self.password.data:
            raise ValidationError('Пароли не совпадают')

app/__init__.py
from flask import Flask, Blueprint
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from config import Config

app = Flask(__name__)
app.config.from_object(Config)
login_blueprint = Blueprint('login_blueprint', __name__, template_folder="templates")
db = SQLAlchemy()
db.init_app(app)
login = LoginManager(app)
login.login_view = 'login_blueprint.login'
migrations = Migrate(app, db, render_as_batch=True)

from app import routes, models
from app.blueprints import user_routes

app/blueprints/user_routes.py
from urllib.parse import urlsplit

from flask import redirect, render_template, request, url_for, flash
from flask_login import logout_user, login_required, login_user, current_user

from app import db, login_blueprint
from app.forms import LoginForm, RegistrationForm
from app.models import User


@login_blueprint.route('/logout')
def logout():
    logout_user()
    return redirect("/")


@login_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or urlsplit(next_page).netloc != '':
            next_page = url_for('index')
            return next_page
        return redirect("/user_panel")
    return render_template('forms/login.html', user=current_user, title='Sign In', form=form)


@login_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User()
        user.name = form.username.data
        user.set_password(form.password.data)
        user.email = form.email.data
        db.session.add(user)
        db.session.commit()
        # login_user(user, remember=form.css.remember_me.data)
        flash('Congratulations, you are now a registered admin!')
        login_user(user, True)
        return redirect(url_for('index'))
    return render_template('forms/register.html', user=current_user, title='Register', form=form)


@login_blueprint.route("/user_panel", methods=['GET', 'POST'])
@login_required
def user_panel():
    return render_template("user_panel.html", user=current_user)

app/routes.py
from flask import render_template, redirect
from flask_login import current_user

from app import app, login
from app.forms import *


@login.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@app.route("/")
def index():
    if current_user.is_authenticated:
        return redirect("user_panel")
    return redirect("login")

app/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% block head %}{% endblock %}
    <link rel="icon" type="image/png" href="/static/images/favicon.ico"/>
    <meta name="yandex-verification" content="18e05c877b8ae73b"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!--Стили-->
    <link rel="stylesheet" type="text/css" href="/static/css/fonts.css">
    <link rel="stylesheet" type="text/css" href="/static/css/custom.css">
    <link rel="stylesheet" type="text/css" href="/static/css/base.css">
    <link rel="stylesheet" type="text/css" href="/static/css/page.css">
    <link rel="stylesheet" type="text/css" href="/static/css/dialog.css">
    <link rel="stylesheet" type="text/css" href="/static/css/animations.css">

    <!--Скрипты-->
    <script type="text/javascript" src="/static/js/dialog.js"></script>
    <script type="text/javascript" src="/static/js/base.js"></script>
    <script src="/static/js/jquery.js"></script>
    <script src="https://kit.fontawesome.com/6957c188ce.js" crossorigin="anonymous"></script>
    <script src="/static/js/site.js"></script>
    <script src="/static/js/navigation.js"></script>
    <script src="https://cdn.ckeditor.com/4.10.0/standard/ckeditor.js"></script>

</head>
<body>

<div id="before">
    {% block before %}{% endblock %}
</div>
<div class="base-content">


    <div class="nav-menu" id="desktop">
<!--        <div class="logo">-->
<!--            <a href="/">-->
<!--                <img src="/static/images/logo.png">-->
<!--            </a>-->
<!--        </div>-->
        {% if not user.is_authenticated %}
        <a class="navigation-buttons" href="{{ url_for('login_blueprint.register') }}">Регистрация</a>
        <a class="navigation-buttons" href="{{ url_for('login_blueprint.login') }}">Вход</a>
        {% endif %}
    </div>

    <div class="nav-menu" id="mobile" style="display: none">
        <div class="nav-controls">
<!--            <div class="logo">-->
<!--                <a href="/">-->
<!--                    <img src="/static/images/logo.png">-->
<!--                </a>-->
<!--            </div>-->

            <a onclick="open_top_menu()" id="open-navigation"><i class="fa-solid fa-bars "></i></a>
            <a style="display: none" id="close-navigation" onclick="close_top_menu()"><i class="fa fa-close"></i></a>
        </div>
        <div id="navigation">
            {% if not user.is_authenticated %}
            <a class="navigation-button" href="{{ url_for('login_blueprint.register') }}">Регистрация</a>
            <a class="navigation-buttons" href="{{ url_for('login_blueprint.login') }}">Вход</a>
            {% endif %}

        </div>

    </div>


    <div id="after">
        {% block after %}{% endblock %}
    </div>


</div>


</body>
</html><!-- cached 2022-11-24 10:12:41 e24cc38881bdebf1e12f84cc0a6bf3ce -->

app/templates/forms/login.html
<!DOCTYPE html>
<html lang="ru">
{% extends "base.html" %}
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{{form._name}}</title>
    <script src="/static/js/form.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/css/form.css">
    {% endblock %}

</head>
<body>


{% block after %}

<div class="form-block">
    <h1 class="title">{{form._name}}</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}

        {{ form.email.label }}
        <p>
            {{ form.email(size=32) }}
            {% for error in form.email.errors %}<br>
            <span class="error">{{ error }}</span>
            {% endfor %}
        </p>
        {{ form.password.label }}
        <p id="password-field" class="password-field">
            {{ form.password(size=32) }}
            <a id="view" onclick="show_password();" class="password-toggle">
                <i id="eye" class="fas fa-eye"></i>
            </a>
            {% for error in form.password.errors %}<br>
            <span class="error">{{ error }}</span>
            {% endfor %}
        </p>

        <p>
            {{ form.remember_me() }}
            {{ form.remember_me.label }}
        </p>
        {{ form.submit() }}

    </form>
</div>
{% endblock %}
</body>
</html>

app/templates/forms/register.html
<!DOCTYPE html>
<html lang="ru">
{% extends "base.html" %}

<head>

    {% block head %}

    <meta charset="UTF-8">
    <title>{{form._name}}</title>
    <script src="/static/js/form.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/css/form.css">

    {% endblock %}
</head>
<body>


{% block after %}
<div class="form-block">
    <h1 class="title">{{form._name}}</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}

        {{ form.username.label }}
        <p>
            {{ form.username(size=32) }}
            {% for error in form.username.errors %}<br>
            <span class="error">{{ error }}</span>
            {% endfor %}
        </p>
        {{ form.email.label }}
        <p>
            {{ form.email(size=32) }}
            {% for error in form.email.errors %}<br>
            <span class="error">{{ error }}</span>
            {% endfor %}
        </p>
        {{ form.password.label }}
        <p id="password-field-1">


            {{ form.password(size=32) }}
            <a class="view" onclick="show_password('password-field-1');">
                <i class='fas fa-eye'></i>
            </a><br>
            {% for error in form.password.errors %}
            <span class="error">{{ error }}</span>
            {% endfor %}
        </p>
        {{ form.password2.label }}
        <p id="password-field-2">
            {{ form.password2(size=32) }}
            <a class="class" onclick="show_password('password-field-2');">
                <i class='fas fa-eye'></i>
            </a><br>
            {% for error in form.password2.errors %}<br>
            <span class="error">{{ error }}</span>
            {% endfor %}
        </p>

        {{ form.submit() }}
    </form>
</div>
{% endblock %}
</body>
</html>

app/templates/user_panel.html
<!DOCTYPE html>
<html lang="ru">
{% extends "base.html" %}

<head>

    {% block head %}

    <meta charset="UTF-8">
    <title>Панель</title>
    <link rel="stylesheet" type="text/css" href="/static/css/user_panel.css">

    {% endblock %}
</head>
<body>


{% block after %}

<div class="container">
    <div class="container-list">
        <ul class="list">
            <li class="list-button">
                <a href="/"><p class="button-text">Кнопка</p></a>
            </li>
        </ul>
    </div>
</div>
{% endblock %}
</body>
</html>